/*Eliminacion de todas las tablas*/
DROP TABLE IF EXISTS PEDIDO_DETALLE;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS PRODUCTO;

/*-------------Creacion de todas las tablas---------------*/
CREATE TABLE USUARIO (
  ID_USUARIO LONG AUTO_INCREMENT  PRIMARY KEY,
  CEDULA VARCHAR(30) NOT NULL UNIQUE,
  NOMBRE VARCHAR(250) NOT NULL,
  DIRECCION VARCHAR(250) NOT NULL,
  TELEFONO VARCHAR(250)
);

CREATE TABLE PRODUCTO (
  ID_PRODUCTO LONG AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(250) NOT NULL,
  VALOR NUMERIC(10,2)
);

CREATE TABLE PEDIDO (
  ID_PEDIDO LONG AUTO_INCREMENT  PRIMARY KEY,
  ID_USUARIO LONG NOT NULL,
  SUBTOTAL NUMERIC(10,2),
  FECHA_CREACION TIMESTAMP,
  ESTADO NUMERIC(1,0),
  foreign key (ID_USUARIO) references USUARIO(ID_USUARIO)
);

CREATE TABLE PEDIDO_DETALLE (
  ID_PEDIDO_DETALLE LONG AUTO_INCREMENT  PRIMARY KEY,
  ID_PEDIDO LONG NOT NULL,
  ID_PRODUCTO LONG NOT NULL,
  foreign key (ID_PEDIDO) references PEDIDO(ID_PEDIDO),
  foreign key (ID_PRODUCTO) references PRODUCTO(ID_PRODUCTO)
);

/*Insercion de los datos a las tablas*/
INSERT INTO USUARIO (ID_USUARIO, CEDULA, NOMBRE, DIRECCION, TELEFONO) VALUES
  (1,'12345', 'Daniel Trujillo', 'Barrio El Recreo','7569856'),
  (2,'98765', 'Esteban Ceron', 'Barrio 7 Agosto','7632569');

INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, VALOR) VALUES
  (1,'teclado',46000.23),
  (2,'mouse',15200.23),
  (3,'pantalla',350000.00);

INSERT INTO PEDIDO (ID_PEDIDO, ID_USUARIO, SUBTOTAL,FECHA_CREACION,ESTADO) VALUES
  (1,1,61200.46,'2021-04-21 4:12:00',1);

 INSERT INTO PEDIDO_DETALLE (ID_PEDIDO_DETALLE, ID_PEDIDO, ID_PRODUCTO) VALUES
  (1,1,1),
  (2,1,2);
  
  
  
  
  
  
  


